### ISSUE TITLE
I do not see any changes in setting sidebar after installing the plugin.

### ISSUE THREAD

**Issue by alekseisasin** [fieldOfView/PrepareStageCompactor#4] opened 2018-07-06 09:06 UTC
After changes in Cura master build the PrepareStageCompactor plugin does not work properly. After starting Cura I do not see any changes in Settings Sidebar. I have used Cura master build.

**Comment by fieldOfView** [comment] 2018-07-24 12:21
It works for me, at least after I started with a clean profile.
Could you add a log so I can see if the plugin loads and/or shows any issues?

**Comment by fieldOfView** [comment] 2018-07-24 12:24
I think this got automatically fixed by changes in Cura.

**Comment by alekseisasin** [comment] 2018-07-25 12:41
I tested in master, and I see the crash:
Application.getInstance()._engine.rootContext().setContextProperty("prepareStageCompactorSettingItemsPath", setting_items_path)
AttributeError: 'CuraApplication' object has no attribute '_engine'

**Comment by fieldOfView** [comment] 2018-07-25 16:53
Are you testing the master branch of the plugin? The master branch does not have that line (the 3.4 branch does).

It could be that there are two versions of the plugin in your install; one in the plugins folder of your cura checkout, and one in the plugins folder of your master configuration folder.

**Comment by alekseisasin** [comment] 2018-07-26 07:57
I was testing in master. 
What I did, I have cloned your plugin and then copied it to Cura plugin folder.

**Comment by fieldOfView** [comment] 2018-07-26 08:44
Please switch your checkout of the plugin to the master branch then. I usually set the default branch for my plugins to match the current release of Cura (3.4 currently). So if you just clone my repository, I think you get the 3.4 branch.

**Comment by fieldOfView** [comment] 2018-08-15 10:15
Closing due to lack of response, and lack of being able to reproduce.

**Closed as completed by fieldOfView** 2018-08-15 10:15 UTC

**Comment by Vandrasc** [comment] 2018-08-20 14:21
Oh nooooo, I also get a crash now, the same errors as Aleksei, when running from master 3.4.99:
{code}
2018-08-20 16:04:39,040 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [65]: An uncaught error has occurred!
2018-08-20 16:04:39,044 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [68]: Traceback (most recent call last):
2018-08-20 16:04:39,050 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [68]:   File "<frozen importlib._bootstrap>", line 969, in _find_and_load
2018-08-20 16:04:39,056 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [68]:   File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
2018-08-20 16:04:39,060 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [68]:   File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
2018-08-20 16:04:39,064 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [68]:   File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
2018-08-20 16:04:39,067 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [68]:   File "__startup__.py", line 12, in <module>
2018-08-20 16:04:39,071 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [68]:   File "<frozen importlib._bootstrap>", line 969, in _find_and_load
2018-08-20 16:04:39,076 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [68]:   File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
2018-08-20 16:04:39,081 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [68]:   File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
2018-08-20 16:04:39,085 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [68]:   File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
2018-08-20 16:04:39,090 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [68]:   File "Console.py", line 24, in <module>
2018-08-20 16:04:39,095 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [68]:   File "X:\master\build\inst\bin\cura_app.py", line 138, in <module>
2018-08-20 16:04:39,100 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [68]:   File "X:\master\build\inst\lib\python3.5\site-packages\cura\CuraApplication.py", line 707, in run
2018-08-20 16:04:39,106 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [68]:   File "X:\master\build\inst\lib\python3.5\site-packages\cura\CuraApplication.py", line 786, in runWithGUI
2018-08-20 16:04:39,111 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [68]:   File "X:\master\build\inst\lib\python3.5\site-packages\UM\Qt\QtApplication.py", line 249, in initializeEngine
2018-08-20 16:04:39,116 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [68]:   File "X:\master\build\inst\lib\python3.5\site-packages\UM\Signal.py", line 212, in emit
2018-08-20 16:04:39,122 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [68]:   File "X:\master\build\inst\lib\python3.5\site-packages\UM\Signal.py", line 315, in __performEmit
2018-08-20 16:04:39,128 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [68]:   File "C:\Users\qa_tester\AppData\Roaming\cura\3.4\plugins\PrepareStageCompactor\PrepareStageCompactor\PrepareStageCompactor.py", line 20, in _engineCreated
2018-08-20 16:04:39,133 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [68]:     Application.getInstance()._engine.rootContext().setContextProperty("prepareStageCompactorSettingItemsPath", setting_items_path)
2018-08-20 16:04:39,139 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [68]: AttributeError: 'CuraApplication' object has no attribute '_engine'
{code}

The plugin installed from the Toolbox contains this data:
"name": "Compact Prepare sidebar",
    "author": "fieldOfView",
    "version": "3.4.0",
    "minimum_cura_version": "3.3",
    "maximum_cura_version": "3.4",
    "description": "Provides a more compact Prepare sidebar in Cura for use on smaller screens",
    "api": 4,
    "i18n-catalog": "cura"

@fieldOfView, there is any other information or logs that I can attach here, that will help you further?

Many thanks!

**Comment by fieldOfView** [comment] 2018-08-20 14:49
What is currently being served from the Toolbox is a version that is compatible with Cura 3.3 and 3.4. You are running master. The plugin does a check to see if the plugin is compatible, but it only does this for releases, not for the master branch of Cura. The "internal" build you are using probably says it is Cura 3.4.99.

Master is always a moving target. I can submit a version of PrepareStageCompactor for current master, but it will likely break before Cura 3.5. So I will push an update when Cura 3.5 is near, or being prepared.

**Comment by Vandrasc** [comment] 2018-08-21 07:00
Ah, of course, I get it now. I will postpone testing the plugin until there is a 3.5 branch, I will keep you posted. It doesn't occur with the rest of your plugins, this being the reason I reported it. 

Thank you for clearing things out.
